<header class="codrops-header">
	<h1>Grupos</h1>
	<nav class="top-menus">
		<a href="<?=$this->hrefCadastrar?>">novo</a> <a
			href="<?=$this->hrefQueCriei?>">que criei</a> <a
			href="<?=$this->hrefQueParticipo?>">que participo</a>
	</nav>
</header>
<div class="component">

	<form id="ui_element" class="sb_wrapper" method="get">
		<p>
			<input class="sb_input" type="text" name="busca" id="email" />
		</p>
		<ul class="sb_dropdown" style="display: none;">
			<li><input type="radio" name="filtro" value="nome" checked="checked" /><label for="Nome do Grupo">Nome do Grupo</label></li>
			<li><input type="radio" name="filtro" value="email" /><label for="E-mail do Lider">Email do Lider</label></li>
		</ul>
		<input class="sb_search" style="background:#f2f2f2 url(<?=$this->searchIcon?>) no-repeat center center;" type="submit" value=""/>
	</form>

	<table border="1">
		<thead>
			<tr>
				<th>Ver</th>
				<th>Grupo</th>
				<th>Lider</th>
				<th>local de encontro</th>
				<th>data de saída</th>
				<th>hora de saída</th>
			</tr>
		</thead>
		<tbody>
	    <?=$this->tbody?>
	    </tbody>
	</table>
</div>

<script type="text/javascript"
	src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
<script type="text/javascript">
            $(function() {
				/**
				* the element
				*/
				var $ui 		= $('#ui_element');
				
				/**
				* on focus and on click display the dropdown, 
				* and change the arrow image
				*/
				$ui.find('.sb_input').bind('focus click',function(){
					$ui.find('.sb_down')
					   .addClass('sb_up')
					   .removeClass('sb_down')
					   .andSelf()
					   .find('.sb_dropdown')
					   .show();
				});
				
				/**
				* on mouse leave hide the dropdown, 
				* and change the arrow image
				*/
				$ui.bind('mouseleave',function(){
					$ui.find('.sb_up')
					   .addClass('sb_down')
					   .removeClass('sb_up')
					   .andSelf()
					   .find('.sb_dropdown')
					   .hide();
				});
				
				/**
				* selecting all checkboxes
				*/
				$ui.find('.sb_dropdown').find('label[for="all"]').prev().bind('click',function(){
					$(this).parent().siblings().find(':checkbox').attr('checked',this.checked).attr('disabled',this.checked);
				});
            });
        </script>


