<tr>
	<td>
    <a href="<?=$this->placeholder('href')->bloquear . '/motorista/' . $this->row->id_motorista?>">
  		Bloquear/Desbloquear
    </a>
  </td>
	<td>
    <?=$this->row->id_motorista?>
  </td>
  <td>
    <?=$this->row->nome_motorista?>
  </td>
	<td>
    <?=$this->row->email?>
  </td>
	<td>
    <?=$this->row->nascimento?>
  </td>
	<td>
    <?=$this->row->bloqueado?>
  </td>

</tr>