<header class="codrops-header">
	<h1><?=$this->header?></h1>
</header>
<div class="component">
	<?php if($this->erro){?>
		<p style="color: red;"><?=$this->erro?></p>
	<?php }?>
	<form method="post">
		<table border="1">
			<tr>
				<td>
					<label for="id">ID</label>
				</td>
				<td>
					<input type="text" id="id" name="id" />
				</td>
			</tr>
			<tr>
				<td>
					<label for="senha">Senha</label>
				</td>
				<td>
					<input type="password" id="senha" name="senha" />
				</td>
			</tr>
			<tr>
				<td>
				</td>
				<td>
					<input type="submit" value="Entrar" />
				</td>
			</tr>			
		</table>
	</form>
</div>